#!/bin/sh
set -e
git fetch origin --prune
git grep -l UNRELEASED-FIXME-AUTOGENERATED-DEBCARGO -- src/*/debian/changelog | cut -d/ -f2 | while read pkg; do
	if ! git show-ref --quiet --verify "refs/remotes/origin/pending-$pkg"; then
		head -n1 src/$pkg/debian/changelog
	fi
done
