overlay = "."
bin = false

[packages."librust-cc-dev"]
summary = "Assist Cargo build scripts in invoking the C compiler - Rust source code"

[packages."librust-cc+rayon-dev"]
summary = "Assist Cargo build scripts in invoking the C compiler - feature \"rayon\""

# TODO: the above could be done in a simpler way in debcargo
